export const list = [
    {
      id: 1,
      cover: "../images/list/p-1.jpg",
      imgSrc: "../images/list/p1.jpg" ,
      kitchen:"../images/list/p5.jpg",
      bathroom:"../imageslist/p3.jpg",
      bedroom:"../imageslist/p14.jpg",
      name: "Incah",
      location: "210 Zirak Road, Canada",
      distance:  0.9,
      status: "available",
      price: "MK200,700",
      type: "Single Room",
      rating: 2.6
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      hostelImages:{
        imgSrc: "../images/list/p3.jpg" ,
      kitchen:"../images/list/p6.jpg",
      bathroom:"../imageslist/p3.jpg",
      bedroom:"../imageslist/p14.jpg",
      },
      name: "Kondwani Hostel",
      location: "5698 Zirak Road, NewYork",
      distance: 3,
      status: "not available",
      price: "MK50,750",
      type: "Shared Room",
      rating: 4.5
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "Kondwani Hostel",
      location: "5698 Zirak Road, NewYork",
      distance: 3,
      status: "not available",
      price: "MK50,750",
      type: "Shared Room",
      rating: 4.5
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "Kondwani Hostel",
      location: "5698 Zirak Road, NewYork",
      distance: 3,
      status: "not available",
      price: "MK50,750",
      type: "Shared Room",
      rating: 4.5
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "Kondwani Hostel",
      location: "5698 Zirak Road, NewYork",
      distance: 3,
      status: "not available",
      price: "MK50,750",
      type: "Shared Room",
      rating: 4.5
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "Kondwani Hostel",
      location: "5698 Zirak Road, NewYork",
      distance: 3,
      status: "not available",
      price: "MK50,750",
      type: "Shared Room",
      rating: 4.5
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "Kondwani Hostel",
      location: "5698 Zirak Road, NewYork",
      distance: 3,
      status: "not available",
      price: "MK50,750",
      type: "Shared Room",
      rating: 4.5
    },
    {
      id: 3,
      cover: "../images/list/p-7.png",
      name: "Fransis Hostel",
      location: "5624 Mooker Market, USA",
      distance: 3.5,
      status: "available",
      price: "MK60,860",
      type: "Single Room",
      rating: 4.6
    },
    {
      id: 4,
      cover: "../images/list/p-4.png",
      name: "HS Hostel",
      location: "5621 Liverpool, London",
      distance: 0.5,
      status: "not available",
      price: "MK257,540",
      type: "Single Room",
      rating: 5.1
    },
    {
      id: 5,
      cover: "../images/list/p-5.png",
      name: "Realty Hostel",
      location: "210 Montreal Road, Canada",
      status: "not available",
      price: "MK260,850",
      type: "Shared Room",
      distance: 0.7,
      rating: 4.1
    },
    {
      id: 6,
      cover: "../images/list/p-6.png",
      name: "Zonse ndi Thawi",
      location: "210 Zirak Road, Canada",
      distance: 2.5,
      status: "not available",
      price: "MK50,742",
      type: "Single Room",
      rating: 2.6
    },
    {
      id: 7,
      cover: "../images/list/p-8.jpg",
      name: "Realty Hostel",
      location: "210 Montreal Road, Canada",
      status: "not available",
      price: "MK260,850",
      type: "Shared Room",
      distance: 0.7,
      rating: 4.2
    },
    {
      id: 8,
      cover: "../images/list/p-9.jpg",
      name: "Zonse ndi Thawi",
      location: "210 Zirak Road, Canada",
      distance: 2.5,
      status: "not available",
      price: "MK50,742",
      type: "Single Room",
      rating: 2.6
    },
   
    {
      id: 5,
      cover: "../images/list/p-5.png",
      name: "Realty Hostel",
      location: "210 Montreal Road, Canada",
      status: "not available",
      price: "MK260,850",
      type: "Shared Room",
      distance: 0.7,
      rating: 4.1
    },
    {
      id: 6,
      cover: "../images/list/p-6.png",
      name: "Zonse ndi Thawi",
      location: "210 Zirak Road, Canada",
      distance: 2.5,
      status: "not available",
      price: "MK50,742",
      type: "Single Room",
      rating: 2.6
    },
    {
      id: 7,
      cover: "../images/list/p-8.jpg",
      name: "Realty Hostel",
      location: "210 Montreal Road, Canada",
      status: "not available",
      price: "MK260,850",
      type: "Shared Room",
      distance: 0.7,
      rating: 4.2
    },
    {
      id: 8,
      cover: "../images/list/p-9.jpg",
      name: "Zonse ndi Thawi",
      location: "210 Zirak Road, Canada",
      distance: 2.5,
      status: "not available",
      price: "MK50,742",
      type: "Single Room",
      rating: 2.6
    },
    
  ]